MONGODB_HOST: mongodb-{{ env }}.daws38sat.fun
REDIS_HOST: redis-{{ env }}.daws38sat.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.daws38sat.fun
MYSQL_HOST: mysql-{{ env }}.daws38sat.fun
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.daws38sat.fun
CART_HOST: cart.backend-alb-{{ env }}.daws38sat.fun
USER_HOST: user.backend-alb-{{ env }}.daws38sat.fun
SHIPPING_HOST: shipping.backend-alb-{{ env }}.daws38sat.fun
PAYMENT_HOST: payment.backend-alb-{{ env }}.daws38sat.fun